name: SonarQube Dev Analysis
on:
  workflow_dispatch:
  # push:
  #   branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  sonar:
    name: Run SonarQube Analysis (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Escaneo en PR ---
      - name: SonarQube Scan (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.TEST_SONAR }}
        with:
          args: >
            -Dsonar.projectKey=srv-ciso:11cert:test
            -Dsonar.projectName=11cert
            -Dsonar.sources=.
